title: "Nic's AI & Tech Rants"
email: nicdunz@gmail.com
description: >-
  Unfiltered commentary on AI, technology, and the culture of innovation. Question the hype, break the mold, and dive deep into what's really happening.
baseurl: ""
url: "https://dicnunz.github.io"
twitter_username: nicdunz
github_username: dicnunz
