title: "Simple Life Hacks"
email: nicdunz@gmail.com
description: >-
  A blog about minimalistic life hacks for the modern world.
baseurl: "" 
url: "https://dicnunz.github.io"
twitter_username: @nicdunz
github_username: dicnunz
